site_name: Svelte Tutorials
nav:
  - Home: index.md
  - Flappy Bird: flappybird.md
  - Web Components: webcomponents.md
  - SvelteKit Firebase Auth: firebase-recipe-site/login.md
  - SvelteKit Firebase SSR: firebase-recipe-site/ssr.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages: ["svelte", "javascript", "html", "css", "typescript"]
extra_css:
  - css/style.css
