site_name: Svelte Tutorials
nav:
  - Home: index.md
  - Flappy Bird: flappybird.md
  - Web Components: webcomponents.md
  - SvelteKit Firebase Auth: firebase-recipe-site/login.md
  - SvelteKit Firebase SSR: firebase-recipe-site/ssr.md
  - SvelteKit Forms: firebase-recipe-site/form.md
  - SvelteKit FireStorage: firebase-recipe-site/upload-picture.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages: ["svelte", "javascript", "html", "css", "typescript"]
extra_css:
  - css/style.css
site_url: https://phptuts.github.io/svelte-docs/
